# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Feridoun.ResToggle
PackageVersion: 1.1.1
InstallerType: portable
Commands:
- res-toggle
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Feridoun/quick-res-change/releases/download/v1.1.1/res_toggle.exe
  InstallerSha256: 7F97C091AABAD3005127F9A5D9D3E41F0EBFC6C7F7B4D48831742E0ABC1B3470
ManifestType: installer
ManifestVersion: 1.10.0
